### ISSUE TITLE
Griddle installation fails

### ISSUE THREAD

**Issue by arr28** [AlexLandau/griddle#16]
- Environment
  - Windows 7 Professional 64-bit
  - Eclipse Kepler SR2
- Process
  - Following installation instructions
  - Added `net.alloyggp.griddle_0.2.0.201507062126.jar` to `C:\Program Files\eclipse.kepler\dropins\plugins\`
  - Restarted Eclipse

Installation apparently unsuccessful.  No knight icon when opening `.kif` files.  Nothing new in the `Open with...` submenu.  No `Add GDL Validation` option in the project's `Configure` submenu.

What diagnostics might be useful?

**Comment by arr28** [comment]
Seems this is because of the version of Eclipse that I'm using (which you did warn me about).  I just installed Luna and tried again with the plugin.  This time it worked fine.  It might be worth you tweaking the wording on your installation instructions to say that they only work with Luna (and possibly later).

I'm happy to stick with Luna (which I already use elsewhere).

**Comment by AlexLandau** [comment]
This version requirement is now noted in the README on the develop branch. It'll make it onto the main project page when I do the next release.
