### ISSUE TITLE
Package into Eclipse update site

### ISSUE THREAD

**Issue by arr28** [AlexLandau/griddle#17]
A suggestion - could you release this in such a way that it can be installed via "Install New Software" from Eclipse?  Should make installation easier and upgrades trivial.

**Comment by AlexLandau** [comment]
Andrew, can you try removing the plugin from Eclipse and try the following as an update site? I want to test that it works for someone else before finalizing the release.

http://alexlandau.github.io/griddle/eclipse/

**Comment by arr28** [comment]
That seems to work.  (I got an unsigned content warning, but once I'd accepted it, installation succeeded.)

Having installed, I get syntax highlighting in .kif files along with build errors if I mess up my GDL.

Thanks!

**Comment by AlexLandau** [comment]
Done, and instructions are now included in the README on master.
